apiVersion: v1
kind: Pod
metadata:
  name: my-nextjs-app
  labels:
    app: front
spec:
  containers:
  - name: nextjs-container
    image: codingalice/aws-wiki-frontend:2.1
    ports:
    - containerPort: 3000
    env:
    - name: API_URL
      value: http://my-django-svc.default.svc.cluster.local:8000
---
apiVersion: v1
kind: Service
metadata:
  name: my-nextjs-svc
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: front

